version: "3.8"
services:
  app:
    build: ./api
    command: python main.py
    ports:
      - "5000:5000"
    volumes:
      - ./api:/api
  magenta: 
    build: ./magenta-testing
    volumes: 
      - ./magenta-testing:/magenta
      - C:/magenta:/magenta-data
    ports: 
      - 6006:6006
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
